import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { PointerEvent as ReactPointerEvent } from 'react'
import { getUiScale, layoutViewportSize, renderedPxToLayoutPx, toLayoutSize } from '@/lib/uiScale'
import { clampRectToBounds, resizeRectFromScreenDelta, type RotatedResizeHandle } from '@/lib/rotatedRectMath'
import type { SettingsWriteSource, SurfaceRectPrefs } from '@/types/store'
export interface RectBounds { minWidth: number; minHeight: number; maxWidth?: number; maxHeight?: number }
export interface RectStorage { getItem(key: string): string | null; setItem(key: string, value: string): void }
export interface LayoutViewport { width: number; height: number }
export interface UsePersistentRectOptions { rect: SurfaceRectPrefs; bounds: RectBounds; onCommit: (rect: SurfaceRectPrefs, source: SettingsWriteSource) => void; snapToEdge?: boolean; preserveAspectRatio?: boolean; aspectRatio?: number; persistGeometry?: string; storage?: RectStorage | null; rotationDeg?: number; mobile?: boolean }
export type DragMode = 'move' | 'n' | 's' | 'e' | 'w' | 'ne' | 'nw' | 'se' | 'sw'
const fallback = { width: 1920, height: 1080 }
const finite = (value: unknown, fallbackValue = 0) => typeof value === 'number' && Number.isFinite(value) ? value : fallbackValue
const same = (a: SurfaceRectPrefs, b: SurfaceRectPrefs) => a.x === b.x && a.y === b.y && a.width === b.width && a.height === b.height
function storageFor(value: RectStorage | null | undefined): RectStorage | undefined { if (value === null) return undefined; if (value) return value; try { return typeof window === 'undefined' ? undefined : window.localStorage } catch { return undefined } }
export function toLayoutBox<T extends { width: number; height: number }>(box: T): LayoutViewport { return toLayoutSize(box, getUiScale()) }
export const viewportBox = (): LayoutViewport => typeof window === 'undefined' ? fallback : layoutViewportSize()
export function clampSurfaceRect(rect: SurfaceRectPrefs, bounds: RectBounds, viewport: LayoutViewport = viewportBox()): SurfaceRectPrefs { const vw = Math.max(1, finite(viewport.width, fallback.width)), vh = Math.max(1, finite(viewport.height, fallback.height)); const minW = Math.min(Math.max(0, finite(bounds.minWidth)), vw), minH = Math.min(Math.max(0, finite(bounds.minHeight)), vh), maxW = Math.min(Math.max(minW, finite(bounds.maxWidth, vw)), vw), maxH = Math.min(Math.max(minH, finite(bounds.maxHeight, vh)), vh); return clampRectToBounds({ x: Math.max(0, finite(rect.x)), y: Math.max(0, finite(rect.y)), width: Math.min(Math.max(minW, finite(rect.width, minW)), maxW), height: Math.min(Math.max(minH, finite(rect.height, minH)), maxH) }, { x: 0, y: 0, width: vw, height: vh }) as SurfaceRectPrefs }
function validRect(value: unknown): value is SurfaceRectPrefs { if (!value || typeof value !== 'object' || Array.isArray(value)) return false; const x = value as Record<string, unknown>; const numbers = ['x','y','width','height'].map(key => x[key]); return numbers.every(item => typeof item === 'number' && Number.isFinite(item)) && (numbers[0] as number) >= 0 && (numbers[1] as number) >= 0 && (numbers[2] as number) > 0 && (numbers[3] as number) > 0 }
export function restorePersistentRect(storage: RectStorage | null | undefined, key: string | undefined, bounds: RectBounds, viewport: LayoutViewport = viewportBox()): SurfaceRectPrefs | undefined { if (!storage || !key) return undefined; try { const parsed: unknown = JSON.parse(storage.getItem(key) ?? ''); return validRect(parsed) ? clampSurfaceRect(parsed, bounds, viewport) : undefined } catch { return undefined } }
export function persistRect(storage: RectStorage | null | undefined, key: string | undefined, rect: SurfaceRectPrefs): boolean { if (!storage || !key || !validRect(rect)) return false; try { storage.setItem(key, JSON.stringify(rect)); return true } catch { return false } }
export function resizeSurfaceRect(start: SurfaceRectPrefs, mode: Exclude<DragMode, 'move'>, dx: number, dy: number, bounds: RectBounds, preserve = false, ratio = start.width / Math.max(1, start.height), rotationDeg = 0): SurfaceRectPrefs { const view = viewportBox(); const opts = { minWidth: Math.min(Math.max(0, finite(bounds.minWidth)), view.width), minHeight: Math.min(Math.max(0, finite(bounds.minHeight)), view.height), maxWidth: Math.min(Math.max(0, finite(bounds.maxWidth, view.width)), view.width), maxHeight: Math.min(Math.max(0, finite(bounds.maxHeight, view.height)), view.height), aspectRatio: preserve && ratio > 0 ? ratio : undefined, bounds: { x: 0, y: 0, width: view.width, height: view.height } }; return resizeRectFromScreenDelta(start, mode, { dx, dy }, rotationDeg, opts) as SurfaceRectPrefs }
export function usePersistentRect(options: UsePersistentRectOptions) {
  const { rect, bounds, onCommit, snapToEdge = false, preserveAspectRatio = false, aspectRatio, persistGeometry, storage, rotationDeg = 0 } = options
  const resolvedStorage = storageFor(storage), initial = useRef<SurfaceRectPrefs | undefined>(undefined), [draft, setDraft] = useState(() => { const restored = restorePersistentRect(resolvedStorage, persistGeometry, bounds); initial.current = restored; return restored ?? clampSurfaceRect(rect, bounds) }), latest = useRef(draft), drag = useRef<{ mode: DragMode; x: number; y: number; rect: SurfaceRectPrefs } | null>(null)
  const config = useRef({ bounds, onCommit, snapToEdge, preserveAspectRatio, aspectRatio, persistGeometry, storage: resolvedStorage, rotationDeg }); config.current = { bounds, onCommit, snapToEdge, preserveAspectRatio, aspectRatio, persistGeometry, storage: resolvedStorage, rotationDeg }
  const save = useCallback((value: SurfaceRectPrefs) => { persistRect(config.current.storage, config.current.persistGeometry, value) }, [])
  useEffect(() => { latest.current = draft }, [draft])
  useEffect(() => { if (initial.current) { save(initial.current); initial.current = undefined } }, [save])
  useEffect(() => { if (drag.current) return; const next = clampSurfaceRect(rect, bounds); if (!same(next, latest.current) && !same(rect, latest.current)) { latest.current = next; setDraft(next) } }, [bounds, rect])
  const commit = useCallback((next: SurfaceRectPrefs, source: SettingsWriteSource = 'automatic-sync') => { let value = clampSurfaceRect(next, config.current.bounds); if (config.current.snapToEdge) { const vw = viewportBox().width; if (value.x <= 24) value = { ...value, x: 0 }; else if (vw - value.x - value.width <= 24) value = { ...value, x: Math.max(0, vw - value.width) } } latest.current = value; setDraft(value); save(value); config.current.onCommit(value, source) }, [save])
  const move = useCallback((event: PointerEvent) => { const active = drag.current; if (!active) return; const scale = getUiScale(), dx = renderedPxToLayoutPx(event.clientX - active.x, scale), dy = renderedPxToLayoutPx(event.clientY - active.y, scale); let next: SurfaceRectPrefs; if (active.mode === 'move') next = { ...active.rect, x: active.rect.x + dx, y: active.rect.y + dy }; else next = clampSurfaceRect(resizeSurfaceRect(active.rect, active.mode as RotatedResizeHandle, dx, dy, config.current.bounds, config.current.preserveAspectRatio, config.current.aspectRatio, config.current.rotationDeg), config.current.bounds); latest.current = next; setDraft(next) }, [])
  const stop = useCallback(() => { if (!drag.current) return; drag.current = null; window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', stop); window.removeEventListener('pointercancel', stop); commit(latest.current, 'user-interaction') }, [commit, move])
  const startDrag = useCallback((mode: DragMode, event: ReactPointerEvent) => { event.preventDefault(); stop(); drag.current = { mode, x: event.clientX, y: event.clientY, rect: latest.current }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', stop); window.addEventListener('pointercancel', stop) }, [move, stop])
  useEffect(() => () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', stop); window.removeEventListener('pointercancel', stop) }, [move, stop])
  return useMemo(() => ({ rect: draft, setRect: commit, startDrag }), [commit, draft, startDrag])
}
