import type { SpindleMountPoint } from 'lumiverse-spindle-types'

/** Canonical 58-literal catalog in spec order. Legacy aliases are not counted here. */
export const HOST_MOUNT_POINTS = [
  'chat_header_left',
  'chat_header_center',
  'chat_header_right',
  'chat_top_dock',
  'chat_bottom_dock',
  'chat_surface_side',
  'chat_sidebar_left',
  'chat_sidebar_right',
  'chat_stream_before',
  'chat_stream_after',
  'chat_empty_state',
  'chat_composer_above',
  'chat_composer_below',
  'chat_input_tools_left',
  'chat_input_tools_right',
  'chat_actions',
  'chat_toolbar',
  'message_header',
  'message_body_before',
  'message_body_after',
  'message_footer',
  'message_actions',
  'message_edit_actions',
  'message_context_menu',
  'message_swipe_indicators',
  'landing_header',
  'landing_hero',
  'landing_characters',
  'landing_recent_chats',
  'landing_footer',
  'sidebar_top',
  'sidebar_bottom',
  'drawer_tab',
  'drawer_header_actions',
  'drawer_footer',
  'character_editor_tab',
  'character_browser_card_actions',
  'preset_editor_tab',
  'preset_editor_toolbar',
  'persona_editor_tab',
  'world_book_entry_table',
  'world_book_entry_row',
  'world_book_entry_editor',
  'world_book_entry_toolbar',
  'lorebook_workspace',
  'lorebook_half_workspace',
  'loom_builder_toolbar',
  'loom_builder_inspector',
  'regex_entry_row',
  'settings_tab',
  'settings_section',
  'settings_card_actions',
  'settings_extensions',
  'modal_header_actions',
  'modal_footer_actions',
  'command_palette_actions',
  'manage_chats_actions',
  'prompt_variables_toolbar',
] as const

/** Pre-58 host literals kept as compatibility aliases. Not counted in the 58. */
export const LEGACY_HOST_MOUNT_POINTS = [
  'sidebar',
  'chat_column_top',
  'landing_toolbar',
  'landing_main',
  'landing_chats',
] as const

export type CanonicalHostMountPoint = (typeof HOST_MOUNT_POINTS)[number]
export type LegacyHostMountPoint = (typeof LEGACY_HOST_MOUNT_POINTS)[number]
export type HostMountPoint = CanonicalHostMountPoint | LegacyHostMountPoint

/** Published points, host-owned points, and third-party anchor ids. */
export type WidenedMountPoint = SpindleMountPoint | HostMountPoint | (string & {})

const knownMountPoints: Readonly<Record<HostMountPoint, true>> = {
  chat_header_left: true,
  chat_header_center: true,
  chat_header_right: true,
  chat_top_dock: true,
  chat_bottom_dock: true,
  chat_surface_side: true,
  chat_sidebar_left: true,
  chat_sidebar_right: true,
  chat_stream_before: true,
  chat_stream_after: true,
  chat_empty_state: true,
  chat_composer_above: true,
  chat_composer_below: true,
  chat_input_tools_left: true,
  chat_input_tools_right: true,
  chat_actions: true,
  chat_toolbar: true,
  message_header: true,
  message_body_before: true,
  message_body_after: true,
  message_footer: true,
  message_actions: true,
  message_edit_actions: true,
  message_context_menu: true,
  message_swipe_indicators: true,
  landing_header: true,
  landing_hero: true,
  landing_characters: true,
  landing_recent_chats: true,
  landing_footer: true,
  sidebar_top: true,
  sidebar_bottom: true,
  drawer_tab: true,
  drawer_header_actions: true,
  drawer_footer: true,
  character_editor_tab: true,
  character_browser_card_actions: true,
  preset_editor_tab: true,
  preset_editor_toolbar: true,
  persona_editor_tab: true,
  world_book_entry_table: true,
  world_book_entry_row: true,
  world_book_entry_editor: true,
  world_book_entry_toolbar: true,
  lorebook_workspace: true,
  lorebook_half_workspace: true,
  loom_builder_toolbar: true,
  loom_builder_inspector: true,
  regex_entry_row: true,
  settings_tab: true,
  settings_section: true,
  settings_card_actions: true,
  settings_extensions: true,
  modal_header_actions: true,
  modal_footer_actions: true,
  command_palette_actions: true,
  manage_chats_actions: true,
  prompt_variables_toolbar: true,
  sidebar: true,
  chat_column_top: true,
  landing_toolbar: true,
  landing_main: true,
  landing_chats: true,
}

export function isKnownMountPoint(point: string): point is HostMountPoint {
  return Object.prototype.hasOwnProperty.call(knownMountPoints, point)
}
