/**
 * Host-enforced limits for every untrusted regex operation.
 *
 * These values are deliberately expressed in UTF-8 bytes rather than JS
 * UTF-16 code units. Callers may choose stricter per-turn values, but an
 * imported script or preset must never raise a host ceiling.
 */
export const REGEX_LIMITS_V1 = Object.freeze({
  maxScripts: 512,
  maxPatterns: 1024,
  maxPatternBytes: 64 * 1024,
  maxReplacementBytes: 128 * 1024,
  maxActionBytes: 16 * 1024,
  maxActionCount: 50,
  maxTrimStrings: 512,
  maxTrimStringBytes: 512,
  maxMatchCount: 1024,
  maxInputBytes: 8 * 1024 * 1024,
  maxOutputBytes: 8 * 1024 * 1024,
  maxExpansionBytes: 16 * 1024 * 1024,
  maxOperationBytes: 2 * 1024 * 1024,
  maxCount: 10_000,
} as const);

const utf8Encoder = new TextEncoder();

export function utf8ByteLength(value: string): number {
  return utf8Encoder.encode(value).byteLength;
}

/** Truncate at a code-point boundary without producing invalid UTF-8. */
export function truncateUtf8(value: string, maxBytes: number): string {
  if (maxBytes <= 0 || value.length === 0) return "";
  if (utf8ByteLength(value) <= maxBytes) return value;
  let end = Math.min(value.length, maxBytes);
  while (end > 0) {
    const candidate = value.slice(0, end);
    if (utf8ByteLength(candidate) <= maxBytes) return candidate;
    end -= 1;
  }
  return "";
}

export type RegexValidationErrorCode =
  | "invalid_input"
  | "invalid_regex"
  | "invalid_flags"
  | "pattern_too_large"
  | "replacement_too_large"
  | "action_too_large"
  | "action_count_exceeded"
  | "trim_string_empty"
  | "trim_string_too_large"
  | "trim_string_invalid"
  | "trim_string_count_exceeded"
  | "script_count_exceeded"
  | "pattern_count_exceeded"
  | "match_limit_exceeded"
  | "output_limit_exceeded"
  | "expansion_limit_exceeded"
  | "operation_limit_exceeded"
  | "queue_full"
  | "zero_progress_transform"
  | "cancelled"
  | "deadline_exceeded"
  | "worker_unavailable"
  | "worker_crashed"
  | "worker_malformed"
  | "worker_timed_out";

const REGEX_VALIDATION_ERROR_CODES: Record<RegexValidationErrorCode, true> = {
  invalid_input: true,
  invalid_regex: true,
  invalid_flags: true,
  pattern_too_large: true,
  replacement_too_large: true,
  action_too_large: true,
  action_count_exceeded: true,
  trim_string_empty: true,
  trim_string_too_large: true,
  trim_string_invalid: true,
  trim_string_count_exceeded: true,
  script_count_exceeded: true,
  pattern_count_exceeded: true,
  match_limit_exceeded: true,
  output_limit_exceeded: true,
  expansion_limit_exceeded: true,
  operation_limit_exceeded: true,
  queue_full: true,
  zero_progress_transform: true,
  cancelled: true,
  deadline_exceeded: true,
  worker_unavailable: true,
  worker_crashed: true,
  worker_malformed: true,
  worker_timed_out: true,
};

export function isRegexValidationErrorCode(value: unknown): value is RegexValidationErrorCode {
  return typeof value === "string"
    && REGEX_VALIDATION_ERROR_CODES[value as RegexValidationErrorCode] === true;
}

export interface RegexValidationFailure {
  readonly code: RegexValidationErrorCode;
  readonly message: string;
}

export class RegexLimitError extends Error {
  constructor(
    public readonly code: RegexValidationErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "RegexLimitError";
  }
}

export class RegexCancelledError extends Error {
  constructor(message = "Regex evaluation was cancelled") {
    super(message);
    this.name = "RegexCancelledError";
  }
}

export class RegexDeadlineError extends RegexLimitError {
  constructor(message = "Regex evaluation exceeded its deadline") {
    super("deadline_exceeded", message);
    this.name = "RegexDeadlineError";
  }
}

/**
 * Counts only bytes generated by replacements/macros, not unchanged source
 * slices. Every caller reserves before constructing a rebuilt output.
 */
export class RegexExpansionBudget {
  private usedBytes = 0;

  constructor(
    public readonly maxBytes = REGEX_LIMITS_V1.maxExpansionBytes,
  ) {}

  get consumedBytes(): number {
    return this.usedBytes;
  }

  remainingBytes(): number {
    return this.maxBytes - this.usedBytes;
  }

  reserve(bytes: number): void {
    if (!Number.isSafeInteger(bytes) || bytes < 0) {
      throw new RegexLimitError("invalid_input", "Invalid regex expansion byte count");
    }
    if (bytes > REGEX_LIMITS_V1.maxOperationBytes) {
      throw new RegexLimitError(
        "operation_limit_exceeded",
        `Regex operation generated more than ${REGEX_LIMITS_V1.maxOperationBytes} bytes`,
      );
    }
    if (this.usedBytes + bytes > this.maxBytes) {
      throw new RegexLimitError(
        "expansion_limit_exceeded",
        `Regex expansion exceeded ${this.maxBytes} bytes`,
      );
    }
    this.usedBytes += bytes;
  }
}

export function assertRegexTextBytes(
  value: string,
  maxBytes: number,
  code: RegexValidationErrorCode,
  label: string,
): void {
  const bytes = utf8ByteLength(value);
  if (bytes > maxBytes) {
    throw new RegexLimitError(code, `${label} exceeds maximum UTF-8 size of ${maxBytes} bytes`);
  }
}

export function throwIfRegexAborted(
  signal?: AbortSignal,
  deadlineAt?: number,
): void {
  if (signal?.aborted) throw new RegexCancelledError();
  if (deadlineAt !== undefined && Date.now() >= deadlineAt) throw new RegexDeadlineError();
}
