export enum EventType {
  // Connection
  CONNECTED = "CONNECTED",

  // Chat lifecycle
  CHAT_CHANGED = "CHAT_CHANGED",
  MESSAGE_SENT = "MESSAGE_SENT",
  MESSAGE_EDITED = "MESSAGE_EDITED",
  MESSAGE_DELETED = "MESSAGE_DELETED",
  MESSAGE_SWIPED = "MESSAGE_SWIPED",
  CHARACTER_MESSAGE_RENDERED = "CHARACTER_MESSAGE_RENDERED",
  USER_MESSAGE_RENDERED = "USER_MESSAGE_RENDERED",

  // Generation
  GENERATION_STARTED = "GENERATION_STARTED",
  GENERATION_ENDED = "GENERATION_ENDED",
  GENERATION_STOPPED = "GENERATION_STOPPED",
  STREAM_TOKEN_RECEIVED = "STREAM_TOKEN_RECEIVED",

  // Entities
  CHARACTER_EDITED = "CHARACTER_EDITED",
  CHARACTER_DELETED = "CHARACTER_DELETED",
  CHARACTER_DUPLICATED = "CHARACTER_DUPLICATED",
  PERSONA_CHANGED = "PERSONA_CHANGED",

  // Images
  IMAGE_UPLOADED = "IMAGE_UPLOADED",
  IMAGE_DELETED = "IMAGE_DELETED",

  // Settings
  SETTINGS_UPDATED = "SETTINGS_UPDATED",
  PRESET_CHANGED = "PRESET_CHANGED",
  CONNECTION_PROFILE_LOADED = "CONNECTION_PROFILE_LOADED",
  MAIN_API_CHANGED = "MAIN_API_CHANGED",
  WORLD_INFO_ACTIVATED = "WORLD_INFO_ACTIVATED",

  // Preset Profiles
  PRESET_PROFILE_CHANGED = "PRESET_PROFILE_CHANGED",

  // Packs
  PACK_CHANGED = "PACK_CHANGED",
  PACK_DELETED = "PACK_DELETED",

  // Council
  COUNCIL_STARTED = "COUNCIL_STARTED",
  COUNCIL_MEMBER_DONE = "COUNCIL_MEMBER_DONE",
  COUNCIL_COMPLETED = "COUNCIL_COMPLETED",

  // Lumi Pipeline
  LUMI_PIPELINE_STARTED = "LUMI_PIPELINE_STARTED",
  LUMI_MODULE_DONE = "LUMI_MODULE_DONE",
  LUMI_PIPELINE_COMPLETED = "LUMI_PIPELINE_COMPLETED",

  // Spindle extension events
  SPINDLE_EXTENSION_LOADED = "SPINDLE_EXTENSION_LOADED",
  SPINDLE_EXTENSION_UNLOADED = "SPINDLE_EXTENSION_UNLOADED",
  SPINDLE_EXTENSION_ERROR = "SPINDLE_EXTENSION_ERROR",
  SPINDLE_FRONTEND_MSG = "SPINDLE_FRONTEND_MSG",
  MESSAGE_TAG_INTERCEPTED = "MESSAGE_TAG_INTERCEPTED",

  // Tool invocation (Spindle extension tools)
  TOOL_INVOCATION = "TOOL_INVOCATION",
}

export interface EventMessage {
  event: EventType;
  payload: any;
  timestamp: number;
  userId?: string;
}
