import type { ThemeConfig } from '@/types/theme'

export const PRESETS: ThemeConfig[] = [
  {
    id: 'lumiverse-purple',
    name: 'Lumiverse Purple',
    mode: 'dark',
    accent: { h: 263, s: 55, l: 65 },
    radiusScale: 1,
    enableGlass: true,
    fontScale: 1,
  },
  {
    id: 'midnight-blue',
    name: 'Midnight Blue',
    mode: 'dark',
    accent: { h: 220, s: 60, l: 60 },
    radiusScale: 1,
    enableGlass: true,
    fontScale: 1,
  },
  {
    id: 'emerald',
    name: 'Emerald',
    mode: 'dark',
    accent: { h: 152, s: 55, l: 55 },
    radiusScale: 1,
    enableGlass: true,
    fontScale: 1,
  },
  {
    id: 'rose',
    name: 'Rose',
    mode: 'dark',
    accent: { h: 340, s: 60, l: 65 },
    radiusScale: 1,
    enableGlass: true,
    fontScale: 1,
  },
  {
    id: 'amber',
    name: 'Amber',
    mode: 'dark',
    accent: { h: 38, s: 65, l: 55 },
    radiusScale: 1,
    enableGlass: true,
    fontScale: 1,
  },
  {
    id: 'slate',
    name: 'Slate',
    mode: 'dark',
    accent: { h: 215, s: 20, l: 55 },
    radiusScale: 1,
    enableGlass: true,
    fontScale: 1,
  },
  {
    id: 'lumiverse-light',
    name: 'Lumiverse Light',
    mode: 'light',
    accent: { h: 263, s: 55, l: 65 },
    radiusScale: 1,
    enableGlass: true,
    fontScale: 1,
  },
  {
    id: 'auto-purple',
    name: 'Auto Purple',
    mode: 'system',
    accent: { h: 263, s: 55, l: 65 },
    radiusScale: 1,
    enableGlass: true,
    fontScale: 1,
  },
  {
    id: 'character-aware',
    name: 'Character Aware',
    mode: 'dark',
    accent: { h: 263, s: 55, l: 65 },
    radiusScale: 1,
    enableGlass: true,
    fontScale: 1,
    characterAware: true,
  },
]

export const DEFAULT_THEME = PRESETS[0]
